#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later
# Install IngeCAD into the user's desktop environment (launcher, icon,
# .dwg/.dxf file association). Safe to re-run after updating the icon.
#
# GNOME Shell only re-reads desktop entries and icons at login: after the
# FIRST install (or an icon change) log out and back in to see the icon.
set -e

HERE=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
BIN="$HOME/.local/bin"
APPS="$HOME/.local/share/applications"
ICONS="$HOME/.local/share/icons/hicolor"
mkdir -p "$BIN" "$APPS" "$ICONS/scalable/apps"

# Launcher script (venv python, repo main.py).
cat > "$BIN/ingecad" <<SH
#!/bin/sh
# IngeCAD launcher (generated by scripts/install-desktop.sh).
exec "$HERE/venv/bin/python" "$HERE/main.py" "\$@"
SH
chmod +x "$BIN/ingecad"

# Desktop entry with an absolute Exec (~/.local/bin may not be in PATH for
# the session that spawns GNOME Shell).
sed "s|^Exec=.*|Exec=$BIN/ingecad %f|" \
    "$HERE/resources/ingecad.desktop" > "$APPS/ingecad.desktop"

# Icon: the scalable SVG plus rasterized sizes. GNOME's icon cache prefers
# pre-rasterized PNGs; regenerating them here keeps every size in sync with
# resources/ingecad.svg.
cp "$HERE/resources/ingecad.svg" "$ICONS/scalable/apps/ingecad.svg"
for s in 16 24 32 48 64 128 256 512; do
    mkdir -p "$ICONS/${s}x${s}/apps"
    if command -v rsvg-convert >/dev/null 2>&1; then
        rsvg-convert -w "$s" -h "$s" "$HERE/resources/ingecad.svg" \
            -o "$ICONS/${s}x${s}/apps/ingecad.png"
    elif command -v inkscape >/dev/null 2>&1; then
        inkscape -w "$s" -h "$s" "$HERE/resources/ingecad.svg" \
            -o "$ICONS/${s}x${s}/apps/ingecad.png" >/dev/null 2>&1
    fi
done

# Document icons for .dwg / .dxf: register a MIME package so the files resolve
# to our branded icon, and install the mimetype PNGs. Cosmetic — it does not
# change which program opens the files.
#
# Icons must land not only in hicolor but in the ACTIVE icon theme (and its
# parents): freedesktop icon lookup scans theme-by-theme, so a theme like Yaru
# that ships a generic "image-x-generic" would otherwise shadow our specific
# "image-vnd.dwg" (which only lives in hicolor, the last theme searched).
ICONS_BASE="$HOME/.local/share/icons"
MIME_DIR="$HOME/.local/share/mime"

install_mime_icons() {  # $1 = theme dir name under ICONS_BASE
    _src_base="$HERE/resources/icons/hicolor"
    [ -d "$_src_base" ] || return 0
    for _s in 16 24 32 48 64 128 256 512; do
        _src="$_src_base/${_s}x${_s}/mimetypes"
        [ -d "$_src" ] || continue
        _dst="$ICONS_BASE/$1/${_s}x${_s}/mimetypes"
        mkdir -p "$_dst"
        cp "$_src"/*.png "$_dst/" 2>/dev/null || true
    done
    command -v gtk-update-icon-cache >/dev/null 2>&1 \
        && gtk-update-icon-cache -f -t "$ICONS_BASE/$1" >/dev/null 2>&1 || true
}

if [ -d "$HERE/resources/icons/hicolor" ] && [ -f "$HERE/resources/mime/ingecad.xml" ]; then
    install_mime_icons hicolor
    # Active icon theme + the themes it inherits (so an "inherits-only" theme
    # such as Yaru-dark gets covered through its parent Yaru).
    THEME=$(gsettings get org.gnome.desktop.interface icon-theme 2>/dev/null \
            | tr -d "'\"" || true)
    THEMES="$THEME"
    for _base in "$ICONS_BASE" /usr/share/icons /usr/local/share/icons; do
        _idx="$_base/$THEME/index.theme"
        if [ -f "$_idx" ]; then
            _inh=$(grep -i '^Inherits' "$_idx" | head -1 | cut -d= -f2 | tr ',' ' ')
            THEMES="$THEMES $_inh"
            break
        fi
    done
    for _t in $THEMES; do
        [ -n "$_t" ] && [ "$_t" != "hicolor" ] && install_mime_icons "$_t"
    done

    mkdir -p "$MIME_DIR/packages"
    cp "$HERE/resources/mime/ingecad.xml" "$MIME_DIR/packages/ingecad.xml"
    command -v update-mime-database >/dev/null 2>&1 \
        && update-mime-database "$MIME_DIR" >/dev/null 2>&1 || true
fi

command -v gtk-update-icon-cache >/dev/null 2>&1 \
    && gtk-update-icon-cache -f "$ICONS" >/dev/null 2>&1 || true
command -v update-desktop-database >/dev/null 2>&1 \
    && update-desktop-database "$APPS" || true
if command -v xdg-mime >/dev/null 2>&1; then
    xdg-mime default ingecad.desktop image/vnd.dwg || true
    xdg-mime default ingecad.desktop image/vnd.dxf || true
fi

echo "IngeCAD installed:"
echo "  launcher : $BIN/ingecad"
echo "  desktop  : $APPS/ingecad.desktop"
echo "  icons    : $ICONS/*/apps/ingecad.*"
echo "  files    : .dwg / .dxf now show a branded document icon"
echo "If the launcher icon does not show yet, log out and back in"
echo "(GNOME Shell only refreshes desktop entries/icons at login)."
echo "For the .dwg/.dxf file icons, reload the file manager (Ctrl+R); if a"
echo "window was already open, restart it with: nautilus -q"
